---

- ansible.builtin.include_tasks: "snap.yml"

- name: Install Telegram
  community.general.snap:
      name: telegram-desktop
      classic: no

- name: Create Telegram Desktop launcher
  ansible.builtin.copy:
    src: /var/lib/snapd/desktop/applications/telegram-desktop_telegram-desktop.desktop
    dest: "/home/{{ username }}/Desktop/"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '755'
    remote_src: yes
    